export const STAFF_SAMPLE_ACTION = 'STAFF_SAMPLE_ACTION';
export const STAFF_ADD_STAFF = 'STAFF_ADD_STAFF';
export const STAFF_SHOW_STAFF = 'STAFF_SHOW_STAFF';
export const STAFF_HIDE_STAFF = 'STAFF_HIDE_STAFF';
export const STAFF_DELETE_STAFF = 'STAFF_DELETE_STAFF';
export const STAFF_EDIT_STAFF = 'STAFF_EDIT_STAFF';
